name: pgoldapp
description: "A financial mobile application built with Flutter."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^3.0.1
  flutter_riverpod: ^3.0.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  http: ^1.4.0

  get_storage: ^2.1.1

  country_picker: ^2.0.25
  flutter_svg: ^2.1.0
  pinput: ^5.0.1
  cached_network_image: ^3.4.1
  transparent_image: ^2.0.1
  loading_progress_indicator: ^0.1.6
  bot_toast: ^4.1.3

  image_picker: ^1.1.2
  file_picker: ^10.2.0
  webview_flutter: ^4.11.0
  open_filex: ^4.7.0
  media_store_plus: ^0.1.3
  screenshot: ^3.0.0
  barcode: ^2.2.9

  finn_utils: ^0.0.3
  dots_indicator: ^4.0.1
  google_fonts: ^6.3.2
  encrypt: ^5.0.3
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
